### PR TITLE
Build system improvements

### PR DESCRIPTION
**Pull request by voodoos**
This PR tries to have as many operations as possible managed by Dune.
The only remaining thing Dune cannot do is pulling the `node_modules` folder.
Now both `esbuild` and `babel` are ran by Dune if necessary.

I was not able to use browserify so I switched to `esbuild` for the compilation phase.

In dev mode it needs to be pulled before build (see `make dev`).
In release mode the promoted `bundle.js` is used directly.
This is explained in comments in the dune file in `includes/dune`.

I also added a simple CI workflow, not sure if it will work or not^^

Of course, these are very opinionated changes so I am open to discussions :-)

### CODE REVIEW

**Comment by voodoos** [comment]
Looks like github actions aren't enabled ?

**Comment by voodoos** [comment]
Hum, I wasn't expecting ocaml-ci to kick in... it doesn't build in release mode so it needs the node_modules. A far as I know there is no way of configuring it...

**Comment by patricoferris** [comment]
Thanks! These changes look really good. I turned ocaml-ci on just in case it was useful, but maybe it isn't?

**Comment by voodoos** [comment]
Ok, I rebased to clean the history a bit (same for my other, tooltip bindings PR).

About the CI, I was expecting Github Actions, not OCaml-CI so I added a workflow file.
I think it is good to have a simple CI, I don't have a strong opinion about which one we should choose.
OCaml-CI is maybe a bit too much since it tests more than 10 configurations... but it is faster.
My github actions workflow does not check ocamlformating like ocaml-ci does.

**Comment by voodoos** [comment]
Any plan to merge it along with #7 ? It is necessary if we want to enable Merlin on the new site playground :-)

**Comment by patricoferris** [comment]
Thanks for this @voodoos \o/, it is a big improvement I think (sorry for the delay)

**Pull request merged**
